- hosts: all
  become: yes
  become_user: root
  tasks:
   - name: Install tree package
     yum:
       name: tree
       state: installed
       update_cache: true

   - name: Unistall tree package
     yum:
       name: tree
       state: removed
